# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myplayer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(795, 600)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 460, 761, 81))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.openAudio = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.openAudio.setObjectName("openAudio")
        self.horizontalLayout_3.addWidget(self.openAudio)
        self.update_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.update_button.setObjectName("update_button")
        self.horizontalLayout_3.addWidget(self.update_button)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.previous_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.previous_button.setObjectName("previous_button")
        self.horizontalLayout_2.addWidget(self.previous_button)
        self.next_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.next_button.setObjectName("next_button")
        self.horizontalLayout_2.addWidget(self.next_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.playButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.playButton.setText("")
        self.playButton.setObjectName("playButton")
        self.horizontalLayout.addWidget(self.playButton)
        self.horizontalSlider = QtWidgets.QSlider(self.horizontalLayoutWidget)
        self.horizontalSlider.setSingleStep(1)
        self.horizontalSlider.setPageStep(1)
        self.horizontalSlider.setTracking(True)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout.addWidget(self.horizontalSlider)
        self.list_queue = QtWidgets.QListWidget(self.centralwidget)
        self.list_queue.setGeometry(QtCore.QRect(440, 10, 341, 441))
        self.list_queue.setObjectName("list_queue")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 795, 26))
        self.menubar.setObjectName("menubar")
        self.options = QtWidgets.QMenu(self.menubar)
        self.options.setObjectName("options")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.playlist = QtWidgets.QAction(MainWindow)
        self.playlist.setObjectName("playlist")
        self.win_options = QtWidgets.QAction(MainWindow)
        self.win_options.setObjectName("win_options")
        self.options.addAction(self.playlist)
        self.options.addSeparator()
        self.options.addAction(self.win_options)
        self.menubar.addAction(self.options.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.openAudio.setText(_translate("MainWindow", "Open music"))
        self.update_button.setText(_translate("MainWindow", "Обновить"))
        self.previous_button.setText(_translate("MainWindow", "<"))
        self.next_button.setText(_translate("MainWindow", ">"))
        self.options.setTitle(_translate("MainWindow", "Окна"))
        self.playlist.setText(_translate("MainWindow", "Плейлисты"))
        self.win_options.setText(_translate("MainWindow", "Настройки"))
